pipeline{
    agent any

    stages{
        stage('Deploy') {
            steps {
                sh '''
                    oc project aibiro-greetings
                    oc start-build greeting-service-2 --follow --wait
                '''
            }
        }
    }
}
